name: muzhiki_core_workspace
description: Melos workspace for Muzhiki packages and apps.
publish_to: none

environment:
  sdk: ^3.12.1

dev_dependencies:
  melos: ^7.3.0
  flutter_lints: ^6.0.0

workspace:
  - packages/muzhiki_ui
  - packages/muzhiki_dependencies
  - packages/muzhiki_bridge
  - packages/muzhiki_support
  - packages/muzhiki_report_problem
  - packages/flutter_appauth
